app {
  name = "EcommerceAnalytics"

  spark {
    master = "local[*]"
    shuffle.partitions = 8
  }

  optimization {
    enable-cache     = true
    enable-broadcast = true
    # Mode de comparaison avant/après (Question 5.3 bonus) :
    # si false, le pipeline s'exécute sans cache ni broadcast
    enabled          = true
  }

  data {
    input {
      transactions = "src/main/resources/data/transactions.csv"
      users        = "src/main/resources/data/users.json"
      products     = "src/main/resources/data/products.parquet"
      merchants    = "src/main/resources/data/merchants.csv"
    }
    output {
      path = "output/"
    }
  }

  validation {
    transaction { min-amount = 0.0, timestamp-length = 14 }
    user        { min-age = 16, max-age = 100, min-income = 0.0 }
    product     { min-price = 0.0, min-rating = 1.0, max-rating = 5.0 }
    merchant    { min-commission = 0.0, max-commission = 1.0 }
  }
}
